### ISSUE TITLE
Add @goodwanghan, @kvnkho, @charlesbluca as recipe maintainers?

### ISSUE THREAD

**Issue by charlesbluca** [conda-forge/fugue-feedstock#6]
### Comment:

Hi @thewchan,

First of all, thanks for your active maintenance on this feedstock 😄 

I'm reaching out to ask if it would be possible to add @goodwanghan (creator of Fugue project), @kvnkho (core maintainer on Fugue), and I (maintainer of dask-sql, a closely related project) as maintainers for this recipe? I'm hopeful that this would significantly ease the burden you've taken on of modifying the recipes for each release, as well as make it easier to coordinate releases between PyPI and conda-forge.

Making this request across the feedstocks for fugue, qpd, and fugue-sql-antlr, which to my knowledge are the main packages which Fugue depends on (though @goodwanghan or @kvnkho can correct me if I'm wrong).

**Comment by kvnkho** [comment]
I was thinking of making this request too! Thanks for beating me to it and thanks for working on this @thewchan!

That is right but also:

triad - https://github.com/conda-forge/triad-feedstock/
adagio - https://github.com/conda-forge/adagio-feedstock

which are utilities for fugue.  Don't know if you want to be included there as well @charlesbluca

**Comment by thewchan** [comment]
@charlesbluca @kvnkho Happy to add you all; just note that updates on Conda Forge is automatically generated when the upstream release is made, so the burden is minimal.

**Comment by charlesbluca** [comment]
> Don't know if you want to be included there as well @charlesbluca

Yup I am cool with be included there as well 🙂

**Comment by thewchan** [comment]
I'm not a maintainer of https://github.com/conda-forge/adagio-feedstock, so someone else will have to add you @charlesbluca.

**Comment by kvnkho** [comment]
I can take care of that I think! Not as knowledgeable as you here @thewchan but I'll give it a shot!
